[workspace]
members = [
    "tests",
    "common/blst",
    "common/types",
    "common/util",
    "contracts/selection",
]

[profile.release]
overflow-checks = true
opt-level = 's'
lto = true
codegen-units = 1
panic = 'abort'
