[workspace]
members = [
    "tests",
    "common/blst",
    "common/protocol",
    "common/secp256k1",
    "common/types",
    "common/util",
    "contracts/selection",
    "contracts/checkpoint",
    "contracts/withdrawal",
    "contracts/stake",
    "contracts/crosschain-metadata",
    "contracts/crosschain-request",
    "contracts/crosschain-lock",
]

[profile.release]
overflow-checks = true
opt-level = 's'
lto = true
codegen-units = 1
panic = 'abort'
