[package]
name = "axon-types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ckb-types = "0.108"
ethereum-types = "0.14"
molecule = "0.7"
