[package]
name = "selection"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axon-types = { path = "../../common/types" }
ckb-std = "0.12"
util = { path = "../../common/util" }
